#!/usr/bin/env python3
"""LIVE proof — AI Kernel Core integration."""
from __future__ import annotations

import json
import os
import sys
import tempfile
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
OUT = os.path.join(ROOT, "data", "ai_kernel_core")
os.makedirs(OUT, exist_ok=True)

results = []


def _utc():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _ok(n, d=""):
    results.append({"test": n, "status": "PASS", "detail": d, "ts": _utc()})


def _fail(n, d=""):
    results.append({"test": n, "status": "FAIL", "detail": d, "ts": _utc()})


print("=" * 60)
print("NOVUS AI KERNEL CORE — LIVE PROOF")
print("=" * 60)

from services.ai_kernel_core.request_router import process_user_request
from services.ai_kernel_core.system_prompt_factory import NOVUSSystemPromptFactory
from services.endpoint_enterprise.yara_engine import reload_engine, get_engine_status, scan_file, generate_yara_rule_draft

reload_engine()
st = get_engine_status()
if st.get("ok") and any("keylogging" in n for n in (st.get("rules_files") or [])):
    _ok("yara_engine_rules", ",".join(st.get("rules_files") or []))
else:
    _fail("yara_engine_rules", str(st))

with tempfile.NamedTemporaryFile(delete=False, suffix=".bin", dir=OUT) as tf:
    tf.write(b"GetAsyncKeyState SetWindowsHookEx BitBlt padding")
    sample = tf.name
try:
    hits = scan_file(sample)
    if hits:
        _ok("yara_live_match", hits[0].get("rule", ""))
    else:
        _fail("yara_live_match", "no hits")
finally:
    try:
        os.unlink(sample)
    except OSError:
        pass

g = process_user_request("Hola")
if g.get("executes_actions") is False:
    _ok("greeting_live", g.get("type", ""))
else:
    _fail("greeting_live", str(g))

iso = process_user_request("Aisla equipo", {"mac": "DE:AD:BE:EF:00:01", "ip": "10.0.0.5"})
if iso.get("executes_network_block") is False and not iso.get("executes_actions"):
    _ok("isolate_recommendation", iso.get("type", ""))
else:
    _fail("isolate_recommendation", str(iso)[:100])

draft = generate_yara_rule_draft("TestPattern", ["GetAsyncKeyState"])
if "NOVUS_AutoGenerated" in draft:
    _ok("yara_draft_generator", "ok")
else:
    _fail("yara_draft_generator", draft[:60])

mod = NOVUSSystemPromptFactory.module_status()
if mod.get("M8_sigma_yara") == "yara_partial_sigma_not_provided":
    _ok("module_status", mod.get("M3_yara_scan", ""))
else:
    _fail("module_status", str(mod))

try:
    import requests
    r = requests.get("http://127.0.0.1:5000/login", timeout=8)
    if r.status_code == 200:
        _ok("http_login_200", str(r.status_code))
    else:
        _fail("http_login_200", str(r.status_code))
except Exception as exc:
    _fail("http_login_200", str(exc)[:80])

pass_n = sum(1 for x in results if x["status"] == "PASS")
fail_n = sum(1 for x in results if x["status"] == "FAIL")

evidence = {
    "module": "ai_kernel_core",
    "generated_at_utc": _utc(),
    "pass": pass_n,
    "fail": fail_n,
    "test_results": results,
    "yara_engine_status": st,
    "sample_yara_hits": hits if "hits" in dir() else [],
    "module_status": mod,
    "sigma_rule": "NOT PROVIDED",
    "yara_rule": "novus_pe_keylogging_screencapture_heuristic.yar",
    "rejected": ["NOVUSNetworkEnforcer iptables/netsh", "yara clásico fallback", "aislamiento autónomo"],
    "executes_network_block": False,
    "invented": False,
}

with open(os.path.join(OUT, "LIVE_PROOF_AI_KERNEL_CORE.json"), "w", encoding="utf-8") as f:
    json.dump(evidence, f, indent=2, ensure_ascii=False)

with open(os.path.join(OUT, "INFORME_AI_KERNEL_CORE.md"), "w", encoding="utf-8") as f:
    f.write(f"""# INFORME AI KERNEL CORE

Generado: {_utc()}

## Resultados LIVE: {pass_n}/{pass_n + fail_n} PASS

## Integrado
- NOVUSSystemPromptFactory → ai_kernel_core + ai_kernel_brain
- Regla YARA PE keylogging → rules/novus_pe_keylogging_screencapture_heuristic.yar (yara-x)
- scan_directory / generate_yara_rule_draft → yara_engine.py
- NOVUSAIKernelCoreEngine → request_router (facade motores existentes)
- audit.jsonl → data/ai_kernel_core/
- kernel_agent hook para escaneo/aislamiento recomendado/aprendizaje

## Rechazado
- YARAFileScannerEngine con yara clásico + fallback regex
- NOVUSNetworkEnforcer (iptables/netsh autónomo)
- NOVUSFeedbackLearningAdapter duplicado (usa knowledge_adapter)
- Veredictos ¡ALERTA DE AMENAZA! sin correlación

## Pendiente
- Regla Sigma (no proporcionada)

Delta madurez oficial: 0
""")

print(f"\nRESULTADO: {pass_n} PASS | {fail_n} FAIL")
print(f"Entregables: {OUT}")
