#!/usr/bin/env python3
"""
Catálogo de playbooks SOPE.
Cada playbook es modular: nombre, descripción, objetivo, nivel de riesgo,
motores participantes, precondiciones, acciones, condiciones de éxito/cancelación.
"""
from __future__ import annotations
from typing import Any, Dict, List

PLAYBOOKS: Dict[str, Dict[str, Any]] = {
    "ransomware": {
        "nombre": "Respuesta a Ransomware",
        "descripcion": "Orquesta la respuesta ante detección de ransomware.",
        "objetivo": "Contener y documentar incidente de ransomware sin destruir evidencia.",
        "nivel_riesgo": "CRITICO",
        "motores": ["btde", "endpoint", "cryptovault", "forense", "swarm", "kernel_ia", "tie", "adaptive_profile", "red", "health_engine"],
        "precondiciones": ["btde_detection", "ransomware_indicators"],
        "acciones": [
            {"id": "observe_endpoint", "tipo": "observe", "descripcion": "Registrar estado del endpoint afectado."},
            {"id": "consult_tie", "tipo": "enrich", "descripcion": "Consultar TIE para IOC relacionados."},
            {"id": "consult_swarm", "tipo": "correlate", "descripcion": "Validar con Swarm si el IOC se ve en otros nodos."},
            {"id": "consult_kernel", "tipo": "analyze", "descripcion": "Kernel IA analiza y propone respuesta."},
            {"id": "generate_forensic", "tipo": "forensic", "descripcion": "Generar cadena de custodia."},
            {"id": "recommend_isolation", "tipo": "recommend", "descripcion": "Recomendar aislamiento del endpoint (requiere nivel >= 2)."},
            {"id": "execute_isolation", "tipo": "execute", "descripcion": "Aislar endpoint (requiere nivel >= 3 y autorización previa).", "destructive": True},
        ],
        "condiciones_exito": ["detection_documented", "forensic_chain_created", "recommendation_generated"],
        "condiciones_cancelacion": ["false_positive_confirmed", "insufficient_evidence"],
    },
    "phishing": {
        "nombre": "Respuesta a Phishing",
        "descripcion": "Orquesta la respuesta ante detección de phishing.",
        "objetivo": "Identificar, documentar y contener ataque de phishing.",
        "nivel_riesgo": "ALTO",
        "motores": ["btde", "web_security", "tie", "kernel_ia", "forense", "swarm", "adaptive_profile"],
        "precondiciones": ["phishing_detection"],
        "acciones": [
            {"id": "observe_email", "tipo": "observe", "descripcion": "Registrar evidencia del correo/URL malicioso."},
            {"id": "enrich_url", "tipo": "enrich", "descripcion": "Consultar TIE para URL/dominio."},
            {"id": "consult_kernel", "tipo": "analyze", "descripcion": "Kernel IA analiza campaña."},
            {"id": "generate_forensic", "tipo": "forensic", "descripcion": "Generar cadena de custodia."},
            {"id": "recommend_block", "tipo": "recommend", "descripcion": "Recomendar bloqueo de URL/dominio (requiere nivel >= 2)."},
        ],
        "condiciones_exito": ["detection_documented", "forensic_chain_created"],
        "condiciones_cancelacion": ["false_positive_confirmed"],
    },
    "malware": {
        "nombre": "Respuesta a Malware",
        "descripcion": "Orquesta la respuesta ante detección de malware.",
        "objetivo": "Contener y documentar incidente de malware.",
        "nivel_riesgo": "ALTO",
        "motores": ["btde", "endpoint", "tie", "kernel_ia", "forense", "swarm", "cryptovault"],
        "precondiciones": ["malware_detection"],
        "acciones": [
            {"id": "observe_process", "tipo": "observe", "descripcion": "Registrar proceso malicioso."},
            {"id": "enrich_hash", "tipo": "enrich", "descripcion": "Consultar TIE para hash del archivo."},
            {"id": "consult_kernel", "tipo": "analyze", "descripcion": "Kernel IA analiza y clasifica."},
            {"id": "generate_forensic", "tipo": "forensic", "descripcion": "Generar cadena de custodia."},
            {"id": "recommend_quarantine", "tipo": "recommend", "descripcion": "Recomendar cuarentena (requiere nivel >= 2)."},
        ],
        "condiciones_exito": ["detection_documented", "forensic_chain_created"],
        "condiciones_cancelacion": ["false_positive_confirmed"],
    },
    "zero_day": {
        "nombre": "Respuesta a Zero-Day",
        "descripcion": "Orquesta la respuesta ante detección de zero-day.",
        "objetivo": "Documentar y contener amenaza zero-day.",
        "nivel_riesgo": "CRITICO",
        "motores": ["zdde", "btde", "tie", "kernel_ia", "forense", "swarm", "endpoint", "red"],
        "precondiciones": ["zero_day_detection"],
        "acciones": [
            {"id": "observe_anomaly", "tipo": "observe", "descripcion": "Registrar anomalía detectada."},
            {"id": "enrich_ioc", "tipo": "enrich", "descripcion": "Consultar TIE para indicadores."},
            {"id": "consult_swarm", "tipo": "correlate", "descripcion": "Validar con Swarm."},
            {"id": "consult_kernel", "tipo": "analyze", "descripcion": "Kernel IA analiza anomalía."},
            {"id": "generate_forensic", "tipo": "forensic", "descripcion": "Generar cadena de custodia."},
            {"id": "recommend_containment", "tipo": "recommend", "descripcion": "Recomendar contención."},
        ],
        "condiciones_exito": ["detection_documented", "forensic_chain_created"],
        "condiciones_cancelacion": ["false_positive_confirmed"],
    },
    "apt": {
        "nombre": "Respuesta a APT",
        "descripcion": "Orquesta respuesta ante amenaza persistente avanzada.",
        "objetivo": "Detectar, documentar y contener APT.",
        "nivel_riesgo": "CRITICO",
        "motores": ["btde", "tie", "kernel_ia", "forense", "swarm", "endpoint", "red", "adaptive_profile"],
        "precondiciones": ["apt_indicators"],
        "acciones": [
            {"id": "observe_indicators", "tipo": "observe", "descripcion": "Registrar indicadores de APT."},
            {"id": "enrich_campaign", "tipo": "enrich", "descripcion": "Consultar TIE para campaña APT."},
            {"id": "consult_kernel", "tipo": "analyze", "descripcion": "Kernel IA correlaciona indicadores."},
            {"id": "generate_forensic", "tipo": "forensic", "descripcion": "Generar cadena de custodia."},
            {"id": "recommend_response", "tipo": "recommend", "descripcion": "Recomendar respuesta escalonada."},
        ],
        "condiciones_exito": ["detection_documented", "forensic_chain_created"],
        "condiciones_cancelacion": ["insufficient_evidence"],
    },
    "botnet": {
        "nombre": "Respuesta a Botnet",
        "descripcion": "Orquesta respuesta ante detección de actividad botnet.",
        "objetivo": "Identificar y contener comunicación C2.",
        "nivel_riesgo": "ALTO",
        "motores": ["btde", "tie", "red", "kernel_ia", "forense", "swarm", "endpoint"],
        "precondiciones": ["botnet_c2_detection"],
        "acciones": [
            {"id": "observe_c2", "tipo": "observe", "descripcion": "Registrar comunicación C2."},
            {"id": "enrich_c2_ip", "tipo": "enrich", "descripcion": "Consultar TIE para IP C2."},
            {"id": "consult_kernel", "tipo": "analyze", "descripcion": "Kernel IA analiza tráfico."},
            {"id": "generate_forensic", "tipo": "forensic", "descripcion": "Generar cadena de custodia."},
            {"id": "recommend_block", "tipo": "recommend", "descripcion": "Recomendar bloqueo de C2."},
        ],
        "condiciones_exito": ["detection_documented", "forensic_chain_created"],
        "condiciones_cancelacion": ["false_positive_confirmed"],
    },
    "lateral_movement": {
        "nombre": "Respuesta a Movimiento Lateral",
        "descripcion": "Orquesta respuesta ante movimiento lateral detectado.",
        "objetivo": "Contener propagación lateral.",
        "nivel_riesgo": "CRITICO",
        "motores": ["btde", "red", "endpoint", "kernel_ia", "forense", "swarm", "adaptive_profile"],
        "precondiciones": ["lateral_movement_detection"],
        "acciones": [
            {"id": "observe_movement", "tipo": "observe", "descripcion": "Registrar movimiento lateral."},
            {"id": "consult_kernel", "tipo": "analyze", "descripcion": "Kernel IA analiza propagación."},
            {"id": "generate_forensic", "tipo": "forensic", "descripcion": "Generar cadena de custodia."},
            {"id": "recommend_segmentation", "tipo": "recommend", "descripcion": "Recomendar segmentación."},
        ],
        "condiciones_exito": ["detection_documented", "forensic_chain_created"],
        "condiciones_cancelacion": ["false_positive_confirmed"],
    },
    "privilege_escalation": {
        "nombre": "Respuesta a Escalada de Privilegios",
        "descripcion": "Orquesta respuesta ante escalada de privilegios.",
        "objetivo": "Documentar y contener escalada de privilegios.",
        "nivel_riesgo": "ALTO",
        "motores": ["btde", "endpoint", "kernel_ia", "forense", "adaptive_profile"],
        "precondiciones": ["privilege_escalation_detection"],
        "acciones": [
            {"id": "observe_escalation", "tipo": "observe", "descripcion": "Registrar escalada."},
            {"id": "consult_kernel", "tipo": "analyze", "descripcion": "Kernel IA analiza."},
            {"id": "generate_forensic", "tipo": "forensic", "descripcion": "Generar cadena de custodia."},
            {"id": "recommend_response", "tipo": "recommend", "descripcion": "Recomendar revocación de privilegios."},
        ],
        "condiciones_exito": ["detection_documented", "forensic_chain_created"],
        "condiciones_cancelacion": ["false_positive_confirmed"],
    },
    "credential_theft": {
        "nombre": "Respuesta a Robo de Credenciales",
        "descripcion": "Orquesta respuesta ante credential theft.",
        "objetivo": "Documentar y contener robo de credenciales.",
        "nivel_riesgo": "CRITICO",
        "motores": ["btde", "endpoint", "kernel_ia", "forense", "cryptovault", "adaptive_profile"],
        "precondiciones": ["credential_theft_detection"],
        "acciones": [
            {"id": "observe_theft", "tipo": "observe", "descripcion": "Registrar indicadores de credential theft."},
            {"id": "consult_kernel", "tipo": "analyze", "descripcion": "Kernel IA analiza."},
            {"id": "generate_forensic", "tipo": "forensic", "descripcion": "Generar cadena de custodia."},
            {"id": "recommend_rotation", "tipo": "recommend", "descripcion": "Recomendar rotación de credenciales."},
        ],
        "condiciones_exito": ["detection_documented", "forensic_chain_created"],
        "condiciones_cancelacion": ["false_positive_confirmed"],
    },
    "exfiltration": {
        "nombre": "Respuesta a Exfiltración",
        "descripcion": "Orquesta respuesta ante exfiltración de datos.",
        "objetivo": "Documentar y contener exfiltración.",
        "nivel_riesgo": "CRITICO",
        "motores": ["btde", "red", "endpoint", "kernel_ia", "forense", "swarm", "cryptovault"],
        "precondiciones": ["exfiltration_detection"],
        "acciones": [
            {"id": "observe_traffic", "tipo": "observe", "descripcion": "Registrar tráfico sospechoso."},
            {"id": "enrich_destination", "tipo": "enrich", "descripcion": "Consultar TIE para destino."},
            {"id": "consult_kernel", "tipo": "analyze", "descripcion": "Kernel IA analiza flujo."},
            {"id": "generate_forensic", "tipo": "forensic", "descripcion": "Generar cadena de custodia."},
            {"id": "recommend_block", "tipo": "recommend", "descripcion": "Recomendar bloqueo de destino."},
        ],
        "condiciones_exito": ["detection_documented", "forensic_chain_created"],
        "condiciones_cancelacion": ["false_positive_confirmed"],
    },
    "brute_force": {
        "nombre": "Respuesta a Fuerza Bruta",
        "descripcion": "Orquesta respuesta ante ataques de fuerza bruta.",
        "objetivo": "Documentar y mitigar ataque de fuerza bruta.",
        "nivel_riesgo": "ALTO",
        "motores": ["btde", "red", "kernel_ia", "forense", "adaptive_profile"],
        "precondiciones": ["brute_force_detection"],
        "acciones": [
            {"id": "observe_attempts", "tipo": "observe", "descripcion": "Registrar intentos fallidos."},
            {"id": "consult_kernel", "tipo": "analyze", "descripcion": "Kernel IA analiza patrón."},
            {"id": "generate_forensic", "tipo": "forensic", "descripcion": "Generar cadena de custodia."},
            {"id": "recommend_lockout", "tipo": "recommend", "descripcion": "Recomendar bloqueo temporal."},
        ],
        "condiciones_exito": ["detection_documented", "forensic_chain_created"],
        "condiciones_cancelacion": ["false_positive_confirmed"],
    },
    "web_attack": {
        "nombre": "Respuesta a Ataque Web",
        "descripcion": "Orquesta respuesta ante ataques web (SQLi, XSS, etc).",
        "objetivo": "Documentar y mitigar ataque web.",
        "nivel_riesgo": "ALTO",
        "motores": ["web_security", "btde", "kernel_ia", "forense", "tie", "red"],
        "precondiciones": ["web_attack_detection"],
        "acciones": [
            {"id": "observe_request", "tipo": "observe", "descripcion": "Registrar request malicioso."},
            {"id": "enrich_source", "tipo": "enrich", "descripcion": "Consultar TIE para IP origen."},
            {"id": "consult_kernel", "tipo": "analyze", "descripcion": "Kernel IA analiza ataque."},
            {"id": "generate_forensic", "tipo": "forensic", "descripcion": "Generar cadena de custodia."},
            {"id": "recommend_waf", "tipo": "recommend", "descripcion": "Recomendar regla WAF."},
        ],
        "condiciones_exito": ["detection_documented", "forensic_chain_created"],
        "condiciones_cancelacion": ["false_positive_confirmed"],
    },
    "insider_threat": {
        "nombre": "Respuesta a Insider Threat",
        "descripcion": "Orquesta respuesta ante amenaza interna.",
        "objetivo": "Documentar y contener amenaza interna sin violar privacidad.",
        "nivel_riesgo": "ALTO",
        "motores": ["btde", "adaptive_profile", "kernel_ia", "forense", "endpoint"],
        "precondiciones": ["insider_threat_detection"],
        "acciones": [
            {"id": "observe_behavior", "tipo": "observe", "descripcion": "Registrar comportamiento anómalo."},
            {"id": "consult_kernel", "tipo": "analyze", "descripcion": "Kernel IA analiza patrón."},
            {"id": "generate_forensic", "tipo": "forensic", "descripcion": "Generar cadena de custodia."},
            {"id": "recommend_investigation", "tipo": "recommend", "descripcion": "Recomendar investigación."},
        ],
        "condiciones_exito": ["detection_documented", "forensic_chain_created"],
        "condiciones_cancelacion": ["insufficient_evidence"],
    },
    "behavior_anomaly": {
        "nombre": "Respuesta a Anomalía de Comportamiento",
        "descripcion": "Orquesta respuesta ante anomalía comportamental.",
        "objetivo": "Investigar y documentar anomalía.",
        "nivel_riesgo": "MEDIO",
        "motores": ["btde", "adaptive_profile", "kernel_ia", "forense"],
        "precondiciones": ["behavior_anomaly_detection"],
        "acciones": [
            {"id": "observe_anomaly", "tipo": "observe", "descripcion": "Registrar anomalía."},
            {"id": "consult_kernel", "tipo": "analyze", "descripcion": "Kernel IA analiza."},
            {"id": "generate_forensic", "tipo": "forensic", "descripcion": "Generar evidencia."},
        ],
        "condiciones_exito": ["detection_documented"],
        "condiciones_cancelacion": ["normal_behavior_confirmed"],
    },
    "compromised_device": {
        "nombre": "Respuesta a Dispositivo Comprometido",
        "descripcion": "Orquesta respuesta ante dispositivo comprometido.",
        "objetivo": "Aislar y documentar dispositivo comprometido.",
        "nivel_riesgo": "CRITICO",
        "motores": ["endpoint", "btde", "red", "kernel_ia", "forense", "swarm", "tie"],
        "precondiciones": ["device_compromise_detection"],
        "acciones": [
            {"id": "observe_device", "tipo": "observe", "descripcion": "Registrar estado del dispositivo."},
            {"id": "enrich_iocs", "tipo": "enrich", "descripcion": "Consultar TIE para IOC."},
            {"id": "consult_kernel", "tipo": "analyze", "descripcion": "Kernel IA analiza."},
            {"id": "generate_forensic", "tipo": "forensic", "descripcion": "Generar cadena de custodia."},
            {"id": "recommend_isolation", "tipo": "recommend", "descripcion": "Recomendar aislamiento."},
        ],
        "condiciones_exito": ["detection_documented", "forensic_chain_created"],
        "condiciones_cancelacion": ["false_positive_confirmed"],
    },
    "suspicious_network": {
        "nombre": "Respuesta a Red Sospechosa",
        "descripcion": "Orquesta respuesta ante red nueva sospechosa.",
        "objetivo": "Investigar y documentar red sospechosa.",
        "nivel_riesgo": "MEDIO",
        "motores": ["red", "btde", "kernel_ia", "forense", "tie"],
        "precondiciones": ["suspicious_network_detection"],
        "acciones": [
            {"id": "observe_network", "tipo": "observe", "descripcion": "Registrar red detectada."},
            {"id": "enrich_network", "tipo": "enrich", "descripcion": "Consultar TIE."},
            {"id": "consult_kernel", "tipo": "analyze", "descripcion": "Kernel IA analiza."},
            {"id": "generate_forensic", "tipo": "forensic", "descripcion": "Generar evidencia."},
        ],
        "condiciones_exito": ["detection_documented"],
        "condiciones_cancelacion": ["legitimate_network_confirmed"],
    },
    "compromised_server": {
        "nombre": "Respuesta a Servidor Comprometido",
        "descripcion": "Orquesta respuesta ante servidor comprometido.",
        "objetivo": "Contener y documentar servidor comprometido.",
        "nivel_riesgo": "CRITICO",
        "motores": ["endpoint", "red", "btde", "kernel_ia", "forense", "swarm", "tie", "health_engine"],
        "precondiciones": ["server_compromise_detection"],
        "acciones": [
            {"id": "observe_server", "tipo": "observe", "descripcion": "Registrar estado del servidor."},
            {"id": "enrich_iocs", "tipo": "enrich", "descripcion": "Consultar TIE."},
            {"id": "consult_kernel", "tipo": "analyze", "descripcion": "Kernel IA analiza."},
            {"id": "generate_forensic", "tipo": "forensic", "descripcion": "Generar cadena de custodia."},
            {"id": "recommend_containment", "tipo": "recommend", "descripcion": "Recomendar contención."},
        ],
        "condiciones_exito": ["detection_documented", "forensic_chain_created"],
        "condiciones_cancelacion": ["false_positive_confirmed"],
    },
    "critical_threat": {
        "nombre": "Respuesta a Amenaza Crítica",
        "descripcion": "Playbook general para amenazas de nivel crítico.",
        "objetivo": "Respuesta integral ante amenaza crítica.",
        "nivel_riesgo": "CRITICO",
        "motores": ["btde", "endpoint", "red", "kernel_ia", "forense", "swarm", "tie", "health_engine", "cryptovault", "adaptive_profile", "compliance", "centro_defensa"],
        "precondiciones": ["critical_threat_detection"],
        "acciones": [
            {"id": "observe_all", "tipo": "observe", "descripcion": "Recopilar toda evidencia disponible."},
            {"id": "enrich_all", "tipo": "enrich", "descripcion": "Consultar todas las fuentes TIE."},
            {"id": "consult_swarm", "tipo": "correlate", "descripcion": "Validar con Swarm."},
            {"id": "consult_kernel", "tipo": "analyze", "descripcion": "Kernel IA análisis integral."},
            {"id": "generate_forensic", "tipo": "forensic", "descripcion": "Generar cadena de custodia completa."},
            {"id": "recommend_response", "tipo": "recommend", "descripcion": "Recomendar respuesta integral."},
        ],
        "condiciones_exito": ["detection_documented", "forensic_chain_created", "recommendation_generated"],
        "condiciones_cancelacion": ["false_positive_confirmed"],
    },
}

PLAYBOOK_IDS = list(PLAYBOOKS.keys())

THREAT_TO_PLAYBOOK = {
    "ransomware": "ransomware",
    "phishing": "phishing",
    "malware": "malware",
    "zero_day": "zero_day",
    "zero-day": "zero_day",
    "apt": "apt",
    "botnet": "botnet",
    "botnet_c2": "botnet",
    "lateral_movement": "lateral_movement",
    "privilege_escalation": "privilege_escalation",
    "credential_theft": "credential_theft",
    "exfiltration": "exfiltration",
    "data_exfiltration": "exfiltration",
    "brute_force": "brute_force",
    "fuerza_bruta": "brute_force",
    "web_attack": "web_attack",
    "sqli": "web_attack",
    "xss": "web_attack",
    "insider_threat": "insider_threat",
    "behavior_anomaly": "behavior_anomaly",
    "anomalia_comportamiento": "behavior_anomaly",
    "compromised_device": "compromised_device",
    "suspicious_network": "suspicious_network",
    "compromised_server": "compromised_server",
    "critical_threat": "critical_threat",
    "amenaza_critica": "critical_threat",
}


def get_playbook(playbook_id: str) -> Dict[str, Any] | None:
    return PLAYBOOKS.get(playbook_id)


def select_playbook(threat_type: str) -> str:
    normalized = threat_type.lower().replace(" ", "_").replace("-", "_")
    return THREAT_TO_PLAYBOOK.get(normalized, "critical_threat")
